### ISSUE TITLE
Search Error

### ISSUE THREAD

**Issue by karthik3625** [BullsEye0/dorks-eye#1]
![Capture](https://user-images.githubusercontent.com/65005163/81794616-afddca80-9528-11ea-9945-fcf2f930c646.JPG)
How to solve this error.

**Comment by BullsEye0** [comment]
https://hackingpassion.com/dorks-eye-google-hacking-dork-scraping-and-searching-script/#Dork_Eye_Search_Install

Just read the article.. The solution is already there..

**Comment by karthik3625** [comment]
> https://hackingpassion.com/dorks-eye-google-hacking-dork-scraping-and-searching-script/#Dork_Eye_Search_Install
> 
> Just read the article.. The solution is already there..

Thank You.

**Comment by karthik3625** [comment]
i am still facing the same error.

**Comment by karthik3625** [comment]
> https://hackingpassion.com/dorks-eye-google-hacking-dork-scraping-and-searching-script/#Dork_Eye_Search_Install
> 
> Just read the article.. The solution is already there..

i am still facing the error even after install python3.
