### ISSUE TITLE
Results

### ISSUE THREAD

**Issue by tathastu871** [BullsEye0/dorks-eye#4]
Showing not more than 100 ds
earch results

**Comment by amralihassan740** [comment]
you can change your code in script to this code below
      
change this
`           counter = counter + 1
            print ("[+] ", counter, results)
            time.sleep(0.1)
            requ += 1
            if requ >= int(amount):
                break
`

to 

`
            counter = counter + 1
            print ("[+] ", counter, results)
            time.sleep(0.1)
            requ += 9
            if requ >= int(amount):
                break
`

the changed which had became in change number 1 to number 9
