### ISSUE TITLE
NameError: name 'search' is not defined

### ISSUE THREAD

**Issue by LtlProfessor** [BullsEye0/dorks-eye#9]
Traceback (most recent call last):
  File "/home/kali/dorks-eye/dorks-eye.py", line 162, in <module>
    dorks()
  File "/home/kali/dorks-eye/dorks-eye.py", line 133, in dorks
    for results in search(dork, tld="com", lang="en", num=int(amount), start=0, stop=None, pause=2):
NameError: name 'search' is not defined

got an error !!!!!!!

im a newbiee ..... please help. me out

**Comment by DrW3b** [comment]
same problem

**Comment by agungprakasa** [comment]
how to fix it?

**Comment by brianeddy2001** [comment]
i am having the same issue and dont know what to do...HELP! error is copied below.

thanks

Traceback (most recent call last):
  File "/root/dorks-eye/dorks-eye.py", line 166, in <module>
    dorks()
  File "/root/dorks-eye/dorks-eye.py", line 137, in dorks
    for results in search(dork, tld="com", lang="en", num=int(amount), start=0, stop=None, pause=2):
NameError: name 'search' is not defined

**Comment by BullsEye0** [comment]
When searching is difficult... Please, my friends.. Google is your best friend in this... Also, I wrote an article about this... So, its very well described. 

https://hackingpassion.com/dorks-eye-google-hacking-dork-scraping-and-searching-script/#dork-eye-search-install

**Comment by ITrackU** [comment]
Hi, even i installed requirements, including googlesearch-python too, (beautifulsoup4, google, soupsieve), i still have the error which search is not defined.

**Comment by yafet-dev** [comment]
name 'search' not defined even thou i installed all requirement, and on your blog you only mentioned installing python3 which i did but having same issue
